"""adding password option for users

Revision ID: 61825c7a58ce
Revises: 25392d69a9f8
Create Date: 2022-08-25 10:48:26.986633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61825c7a58ce'
down_revision = '25392d69a9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
