"""empty message

Revision ID: a38e647a5ff9
Revises: bb1bd0ce5c4a
Create Date: 2022-08-30 15:19:43.933734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38e647a5ff9'
down_revision = 'bb1bd0ce5c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('device_model', sa.String(length=128), nullable=True),
    sa.Column('assigned_to', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_serial_number'), 'assets', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_serial_number'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
